btdht_search/urls.py
# -*- coding: utf-8 -*-
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License version 3 for
# more details.
#
# You should have received a copy of the GNU General Public License version 3
# along with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# (c) 2015-2016 Valentin Samir
"""urls for the app"""
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from .utils import require_login, token_auth

import views

app_name = "btdht_search"

urlpatterns = [
    url('^$', require_login(views.index), name='index'),
    url(
        '^download/(?P<hex_hash>[0-9A-Fa-f]{40})/(?P<name>.*)\.torrent$',
        require_login(views.download_torrent),
        name='download_torrent'
    ),
    url(
        (
            'api/auth/^(?P<token>[0-9A-Fa-f]{32})/download/'
            '(?P<hex_hash>[0-9A-Fa-f]{40})/(?P<name>.*)\.torrent$'
        ),
        token_auth(views.download_torrent),
        name='download_torrent'
    ),
    url(
        '^torrent/(?P<hex_hash>[0-9A-Fa-f]{40})/(?P<name>.*)?$',
        require_login(views.info_torrent),
        name='info_torrent'
    ),
    url(
        '^api/torrent/(?P<hex_hash>[0-9A-Fa-f]{40}).json$',
        require_login(views.api_info_torrent),
        name='api_info_torrent'
    ),
    url(
        '^api/auth/(?P<token>[0-9A-Fa-f]{32})/torrent/(?P<hex_hash>[0-9A-Fa-f]{40}).json$',
        token_auth(views.api_info_torrent),
        name='api_info_torrent_token'
    ),
    url(
        (
            '^search/(?P<query>.*)/(?P<page>[0-9]+)/(?P<order_by>[1-7])/'
            '(?P<asc>[0-1])/(?P<category>[0-7])$'
        ),
        require_login(views.index),
        name='index_query'
    ),
    url(
        (
            '^api/search/(?P<query>.*)/(?P<page>[0-9]+)/(?P<order_by>[1-7])/'
            '(?P<asc>[0-1])/(?P<category>[0-7]).json'
        ),
        require_login(views.api_search),
        name='api_search'
    ),
    url(
        (
            '^api/auth/(?P<token>[0-9A-Fa-f]{32})/search/(?P<query>.*)/(?P<page>[0-9]+)/',
            '(?P<order_by>[1-7])/(?P<asc>[0-1])/(?P<category>[0-7]).json'
        ),
        token_auth(views.api_search),
        name='api_search_token'
    ),
    url('^autocomplete$', require_login(views.autocomplete), name="autocomplete"),
    url('^recent$', require_login(views.recent), name='recent_index'),
    url('^api/recent.json$', require_login(views.api_recent), name='api_recent_index'),
    url('^recent/(?P<category>[0-7])/(?P<page>[0-9]+)$', require_login(views.recent), name='recent'),
    url('^rss/recent/(?P<category>[0-7])$', require_login(cache_page(60)(views.RecentFeed())), name='recent_rss'),
    url('^api/recent/(?P<category>[0-7])/(?P<page>[0-9]+).json', require_login(views.api_recent), name='api_recent'),
    url(
        '^api/auth/(?P<token>[0-9A-Fa-f]{32})/recent.json$',
        token_auth(views.api_recent),
        name='api_recent_index_token'
    ),
    url(
        '^api/auth/(?P<token>[0-9A-Fa-f]{32})/recent/(?P<category>[0-7])/(?P<page>[0-9]+).json',
        token_auth(views.api_recent),
        name='api_recent_token'
    ),
    url('^top$', require_login(views.top), name='top_index'),
    url('^api/top.json', require_login(views.api_top), name='api_recent_index'),
    url('^top/(?P<category>[0-7])/(?P<page>[0-9]+)$', require_login(views.top), name='top'),
    url('^rss/top/(?P<category>[0-7])$', require_login(cache_page(60)(views.TopFeed())), name='top_rss'),
    url('^api/top/(?P<category>[0-7])/(?P<page>[0-9]+).json$', require_login(views.api_top), name='api_top'),
    url(
        '^api/auth/(?P<token>[0-9A-Fa-f]{32})/top.json$',
        token_auth(views.api_top),
        name='api_top_index_token'
    ),
    url(
        '^api/auth/(?P<token>[0-9A-Fa-f]{32})/top/(?P<category>[0-7])/(?P<page>[0-9]+).json',
        token_auth(views.api_top),
        name='api_top_token'
    ),
    url('^stats$', require_login(views.stats), name='stats'),
    url('^api$', require_login(views.api), name='api'),
    url('^about$', require_login(views.about), name='about'),
    url("^sitemap.xml.gz", require_login(views.sitemap), name="sitemap_index"),
    url("^sitemap/(?P<file>[0-9A-Za-z\.]+)", require_login(views.sitemap), name="sitemap"),
    url("^robots.txt$", require_login(views.robots_txt), name="robots.txt"),
    url("^dmca$", require_login(views.dmca), name="dmca"),
    url("^legal$", require_login(views.legal), name="legal"),
]

btdht_search/forms.py
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License version 3 for
# more details.
#
# You should have received a copy of the GNU General Public License version 3
# along with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# (c) 2015-2016 Valentin Samir
"""forms for the app"""
from django import forms
from django.forms import widgets

from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget

import const


class BootsrapForm(forms.Form):
    """
        Bases: :class:`django.forms.Form`

        Form base class to use boostrap then rendering the form fields
    """
    def __init__(self, *args, **kwargs):
        super(BootsrapForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            # Only tweak the field if it will be displayed
            if not isinstance(field.widget, widgets.HiddenInput):
                attrs = {}
                if (
                    isinstance(field.widget, (widgets.Input, widgets.Select, widgets.Textarea)) and
                    not isinstance(field.widget, (forms.RadioSelect,))
                ):
                    attrs['class'] = "form-control"
                if isinstance(field.widget, (widgets.Input, widgets.Textarea)) and field.label:
                    attrs["placeholder"] = field.label
                if field.required:
                    attrs["required"] = "required"
                field.widget.attrs.update(attrs)


class SearchForm(BootsrapForm):
    query = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={
            'placeholder': 'Search here',
        })
    )
    category = forms.ChoiceField(
        label="",
        choices=const.categories_choices,
        widget=forms.RadioSelect(),
    )


class CaptchaForm(BootsrapForm):
    captcha = ReCaptchaField(widget=ReCaptchaWidget(), label="")

btdht_search/templates/btdht_search/about.html
{% extends "btdht_search/base.html" %}
{% load i18n %}
{% load btdht_search %}

{% block title %}BTDHT | About{% endblock %}

{% block content2 %}
<h1>Overview</h1>
<p>
<a href="{{""|absolute_url:request}}">BTDHT Search</a> is a BitTorrent DHT search engine.<br/>
BitTorrent is a file sharing protocol.<br/>
DHT stand for Distributed Hash Table, the bittorent DHT, is a decentralized database used to find
peers distributing content.<br/>
A torrent is a file with metadata which describes distributed content.
</p>

<p>
BTDHT Search's database is formed by DHT users.<br/>
BTDHT Search participates in the bittorent DHT network and follows the bittorent DHT protocol specification.<br/>
The project name is an acronym for Bittorrent Distributed Hash Table Search.
</p>

<p>
BTDHT Search is not a tracker and doesn't store any content and only collects
torrent metadata (such as file names and file sizes) and a magnet link (torrent identifier).
</p>

<p>
BTDHT Search is fully automated and no one but the automated program crawling the DHT is adding torrents metadata to the database.
</p>

<h1>Contact</h1>

{% if settings.BTDHT_CONTACT_MAILHIDE_URL or settings.BTDHT_CONTACT_EMAIL %}
<p>
If you have any question, you can contact the site webmaster by mail
{% if settings.BTDHT_CONTACT_MAILHIDE_URL %}by clicking
<a
  href="{{settings.BTDHT_CONTACT_MAILHIDE_URL.0|safe}}"
  onclick="window.open(
    '{{settings.BTDHT_CONTACT_MAILHIDE_URL.1|safe}}',
    '',
    'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300'
  ); return false;"
  title="Reveal this e-mail address">here</a>.
{% else %}at the address <a href="mailto:{{settings.BTDHT_CONTACT_EMAIL}}">{{settings.BTDHT_CONTACT_EMAIL}}</a>{% endif %}
<p>

<h1>Legal</h1>
{% if settings.BTDHT_LEGAL_ENABLE %}<p>You will find our legal notice <a href="{% url "btdht_search:legal" %}">here</a>.<p>{% endif %}
<p>
You will find the list of torrents found crawling the DHT that are no longer indexed due to a DMCA request or equivalent <a href="{% url "btdht_search:dmca" %}">here</a>
{% endif %}
{% endblock %}

btdht_search/templates/btdht_search/api.html
{% extends "btdht_search/base.html" %}
{% load i18n %}
{% load btdht_search %}

{% block title %}BTDHT | API{% endblock %}

{% block content2 %}
<h1>API</h1>
{% if request.user.is_authenticated and user_pref %}
<p>You API token: <pre>{{user_pref.token}}</pre></p>
{% endif %}
<p>
<p>You can consult the database using the JSON following json API:</p>
<ul>
  <li>
    For fetcthing search results :
    {% url "btdht_search:api_search" "AZERTYUIOP" 1 2 0 4 as search_url %}
    <pre>{{search_url|replace:"AZERTYUIOP:<query>"|replace:"1:<page_nb>"|replace:"2:<orderby_id>"|replace:"0:<asc>"|replace:"4:<category_id>"|absolute_url:request}}</pre>
    Categories ids are:
    <ul>
      <li>all: 0</li>
    {% for cat in const.categories %}
      <li>{{cat}}: {{forloop.counter}}</li>
    {% endfor %}
    </ul>
    Order ids are:
    <ul>
    {% for order, id in const.order_by %}
      <li>{{order}}: {{id}}</li>
    {% endfor %}
    </ul>
    <p>Set asc to 1 for sorting in ascending order, and 0 for descending order.</p>
    For instance, search for "debian", return the first result page, order by pertinence (score), descending order (more pertinent results, first), results from all categories:
{% url "btdht_search:api_search" "debian" 1 1 1 0 as search_url %}
<pre>
$ curl {{search_url|absolute_url:request}}
[
 {
  "peers": 0, 
  "seeds": 1, 
  "hash": "7661229811ef32014879ceedcdf4a48f256c88ba", 
  "name": "debian-8.4.0-i386-netinst.iso", 
  "complete": 0, 
  "created": 1477188735, 
  "last_scrape": 1477319941, 
  "file_nb": 1, 
  "score": 0.5714285714285714, 
  "size": 331350016
 }, 
 {
  "peers": 0, 
  "seeds": 0, 
  "hash": "3abddf1c551b4a5da02413dcd71fce0599e01d04", 
  "name": "debian-8.0.0-i386-netinst.iso", 
  "complete": 0, 
  "created": 1477014396, 
  "last_scrape": 1477319941, 
  "file_nb": 1, 
  "score": 0.5714285714285714, 
  "size": 330301440
 }, 
...
]
</pre>
  </li>
  <li>
  For reading a specific torrent info:
  {% url "btdht_search:api_info_torrent" "EFF64C9D27332054112405897710C51BB3DBB6DD" as torrent_url%}
  <pre>{{torrent_url|replace:"EFF64C9D27332054112405897710C51BB3DBB6DD:<torrent hex hash>"|absolute_url:request}}</pre>
  For instance :
  {% url "btdht_search:api_info_torrent" "7661229811ef32014879ceedcdf4a48f256c88ba" as torrent_url%}
<pre>
$ curl {{torrent_url|absolute_url:request}}
{
 "peers": 0, 
 "seeds": 1, 
 "hash": "7661229811ef32014879ceedcdf4a48f256c88ba", 
 "name": "debian-8.4.0-i386-netinst.iso", 
 "complete": 0, 
 "created": 1477188735, 
 "last_scrape": 1477319941, 
 "file_nb": 1, 
 "size": 331350016
}
</pre>
  </li>
  <li>
  Fetching recent torrents:
  {% url "btdht_search:api_recent" 1 2 as recent_url %}
  <pre>{{recent_url|replace:"1:<category_id>"|replace:"2:<page_nb>"|absolute_url:request}}</pre>
  For instance:
{% url "btdht_search:api_recent" 0 1 as recent_url %}
<pre>
$ curl {{recent_url|absolute_url:request}}
[
 {
  "peers": 9, 
  "seeds": 10, 
  "hash": "410660b3744984876f31c68d2dd2cf56e4a5d3af", 
  "name": "SNIS-659FHD.mp4", 
  "complete": 1637, 
  "created": 1477321297, 
  "last_scrape": 1477321383, 
  "file_nb": 1, 
  "size": 7470086567
 }, 
 {
  "peers": 0, 
  "seeds": 12, 
  "hash": "a61776bf5d01764a338296166ccdea7287fa49ca", 
  "name": "The.Wave.2016.TRUEFRENCH.DVDRIP-www.lien-torrent.com.com.avi", 
  "complete": 15, 
  "created": 1477321297, 
  "last_scrape": 1477321383, 
  "file_nb": 1, 
  "size": 1137139826
 }, 
...
]
</pre>
  </li>
  <li>
  Fetching top torrents:
  {% url "btdht_search:api_top" 1 2 as top_url %}
  <pre>{{top_url|replace:"1:<category_id>"|replace:"2:<page_nb>"|absolute_url:request}}</pre>
  For instance:
{% url "btdht_search:api_top" 0 1 as top_url %}
<pre>
$ curl {{top_url|absolute_url:request}}
[
 {
  "hash": "4e803a9d07492a5e8558d441b2a87b2b4ed67fde",
  "complete": 48397,
  "last_scrape": 1482774594,
  "file_nb": 2,
  "categories": [
   "video"
  ],
  "size": 989948328,
  "peers": 7843,
  "name": "The Accountant (2016) [YTS.AG]",
  "created": 1482610224,
  "magnet": "magnet:?xt=urn:btih:4e803a9d07492a5e8558d441b2a87b2b4ed67fde&db=The%20Accountant%20%282016%29%20%5BYTS.AG%5D&tr=...",
  "seeds": 8299
 },
...
]
</pre>
  </li>
</ul>
Page 1 always exists. You will get a 404 not found error if trying to fetch above the last page
{% endblock %}

btdht_search/templates/btdht_search/base.html
{% load i18n %}{% load staticfiles %}{% load cookielaw_tags %}{% get_current_language as LANGUAGE_CODE %}<!DOCTYPE html>
<html{% if LANGUAGE_CODE %} lang="{{LANGUAGE_CODE}}"{% endif %}>
    <head>
        <meta charset="utf-8">
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% trans "BTDHT Search"  %}{% endblock %}</title>
        {% block extra_pre_head %}{% endblock %}
        <meta name="description" content="A bittorrent DHT search engine: search for torrents in the bittorrent's Distributed Hash Table">
        <link rel="sitemap" type="application/xml" title="Sitemap" href="{% url "btdht_search:sitemap_index" %}">
        <link rel="stylesheet" href="{{settings.BTDHT_COMPONENT_URLS.jqueryui_css}}">
        <link href="{{settings.BTDHT_COMPONENT_URLS.bootstrap3_css}}" rel="stylesheet">
        <link href="{{settings.BTDHT_COMPONENT_URLS.fontawesome}}" rel="stylesheet">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="{{settings.BTDHT_COMPONENT_URLS.html5shiv}}"></script>
        <script src="{{settings.BTDHT_COMPONENT_URLS.respond}}"></script>
        <![endif]-->
        {% if settings.BTDHT_FAVICON_URL %}<link rel="shortcut icon" href="{{settings.BTDHT_FAVICON_URL}}" />{% endif %}
        {% block extra_head %}{% endblock %}
        <link href="{% static "btdht_search/bootstrap-social.css" %}" rel="stylesheet">
        <link href="{% static "btdht_search/styles.css" %}" rel="stylesheet">
    </head>
    <body>
    <!-- detected county {{country_code}} -->
    {% cookielaw_banner %}
    {% include "btdht_search/navbar.html" %}
      <div id="wrap">
        <div class="container">
           {% block container %}
           {% block pre_content %}{% endblock %}
            <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-2 col-xs-0"></div>
            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
            {% include "btdht_search/messages.html" %}
            {% block content %}{% endblock %}
            </div>
            <div class="col-lg-3 col-md-3 col-sm-2 col-xs-0"></div>
            </div>
            <div class="row" id="content2">{% block content2 %}{% endblock %}</div>
        {% endblock %}
        </div> <!-- /container -->
       </div>
     <div style="clear: both;"></div>
      <script src="{{settings.BTDHT_COMPONENT_URLS.jquery}}"></script>
      <script src="{{settings.BTDHT_COMPONENT_URLS.jqueryui_js}}"></script>
      <script src="{{settings.BTDHT_COMPONENT_URLS.jquery_cookie}}"></script>
      <script src="{{settings.BTDHT_COMPONENT_URLS.bootstrap3_js}}"></script>
      <script src="{% static "cookielaw/js/cookielaw.js" %}"></script>
      <script src="{% static "btdht_search/responsive-paginate.js" %}"></script>
      <script src="{% static "btdht_search/favorites.js" %}"></script>
      {% block javascript %}{% endblock %}
      <script type="text/javascript">
populate_favorite_navbar();
if($.cookie('timezone') == null){
    $.getScript("{{settings.BTDHT_COMPONENT_URLS.jstz}}", function(){
        var timezone = jstz.determine();
        $.cookie('timezone', timezone.name(), { expires: 365 * 100, path: '/' });
        location.reload();
    });
}
$('#srch-term').autocomplete({
      source: "{% url "btdht_search:autocomplete" %}",
      minLength: 1,
});
{% block javascript_inline %}{% endblock %}
</script>
    </body>
</html>

btdht_search/templates/btdht_search/navbar.html
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container" id="navbar-container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "btdht_search:index" %}">
              {% if settings.BTDHT_LOGO_URL %}<span><img src="{{settings.BTDHT_LOGO_URL}}" alt="btdht-logo"/></span>{% endif %}
              BTDHT Search
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% url "btdht_search:index" as index_url %}
            {% url "btdht_search:recent_index" as recent_url %}
            {% url "btdht_search:top_index" as top_url %}
            {% url "btdht_search:stats" as stats_url %}
            {% url "btdht_search:api" as api_url %}
            {% url "btdht_search:about" as about_url %}
            <li{% if request.path == index_url %} class="active"{% endif %}>
              <a href="{{index_url}}" title="Home"><span class="hidden-sm">Home</span><span class="glyphicon glyphicon-home visible-sm"></span></a>
            </li>
            <li class="dropdown{% if recent_url in request.path or top_url in request.path %} active{% endif %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="hidden-sm">Explore <span class="caret"></span></span>
                  <span class="glyphicon glyphicon-plus visible-sm"></span>
              </a>
              <ul class="dropdown-menu">
                <li{% if recent_url in request.path %} class="active"{% endif %}><a href="{{recent_url}}">Recent torrents</a></li>
                <li{% if top_url in request.path %} class="active"{% endif %}><a href="{{top_url}}">Top torrents</a></li>
              </ul>
            </li>
            <li class="dropdown" id="favorites_navbar" style="display: none">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="Favorites">
                <span class="hidden-sm">Favorites <span class="caret"></span></span>
                <span class="glyphicon glyphicon-star visible-sm"></span>
              </a>
              <ul class="dropdown-menu" id="favorites_dropdown">
              </ul>
            </li>
            <li{% if stats_url == request.path %} class="active"{% endif %}>
              <a href="{{stats_url}}" title="Statistics"><span class="hidden-sm">Statistics</span><span class="glyphicon glyphicon-stats visible-sm"></span></a>
            </li>
            <li{% if api_url == request.path %} class="active"{% endif %}>
              <a href="{{api_url}}" title="API"><span class="hidden-sm">API</span><span class="glyphicon glyphicon-tasks visible-sm"></span></a>
            </li>
            <li{% if about_url == request.path %} class="active"{% endif %}>
              <a href="{{about_url}}" title="About"><span class="hidden-sm">About</span><span class="glyphicon glyphicon-info-sign visible-sm"></span></a>
            </li>
          </ul>
          {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url "logout" %}"><span class="glyphicon glyphicon-off"</span></a></li>
          </ul>
          {% endif %}
          <form class="navbar-form navbar-right" role="search" method="post" action="{% url "btdht_search:index" %}">
            {% csrf_token %}
            <div class="input-group" id="navbar-search-input-group">
              <input type="text" class="form-control" placeholder="Search" name="query" id="srch-term" value="{% if query %}{{query}}{% elif request.session.query %}{{request.session.query}}{% endif %}" required="">
              <div class="input-group-btn" id="navbar-search-input-group-btn">
              <select id="nav-search-select" class="form-control select-noarrow" name="category">
              {% for value in const.categories_choices %}
              <option value="{{value.0}}" {% if category == value.0 or request.session.category == value.0 %}selected{% endif %} >{{value.1}}</option>
              {% endfor %}
              </select>
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
            </div>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

btdht_search/templates/btdht_search/recent.html
{% extends "btdht_search/base.html" %}
{% load i18n %}
{% load btdht_search %}

{% block title %}BTDHT | recent torrents{% if torrents.page > 1 %}, page {{torrents.page}}{% endif %}{% endblock %}
{% block extra_head %}
<link rel="alternate" type="application/rss+xml" href="{% url "btdht_search:recent_rss" category %}" title="rss"/>
{% endblock %}

{% block pre_content %}
<div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h1 id="app-name">
                    {% if settings.BTDHT_LOGO_URL %}<img src="{{settings.BTDHT_LOGO_URL}}" alt="btdht-logo" />{% endif %}
                    {% trans "BTDHT Search" %}
                </h1>
              </div>
            </div>
{% endblock %}


{% block content2 %}
{% if settings.BTDHT_ADS_TEMPLATE %}{% include settings.BTDHT_ADS_TEMPLATE %}{% endif %}
<h1 id="recent">
Recent torrents
<a href="{% url "btdht_search:recent_rss" category %}"><i class="fa fa-rss pull-right" aria-hidden="true" style="color:#fb8c00"></i></a>
</h1>
<div class="text-center">
<a class="btn btn-default{% if category == 0 %} active{% endif %}" href="{% if torrents.page == 1 %}{% url "btdht_search:recent_index" %}{% else %}{% url "btdht_search:recent" 0 torrents.page %}{% endif %}">All</a>
{% for cat in const.categories %}
<a class="btn btn-default{% if category == forloop.counter %} active{% endif %}" href="{% url "btdht_search:recent" forloop.counter torrents.page %}">{{cat}}</a>
{% endfor %}
</div>
<br/>
{% include "btdht_search/torrent_table.html" %}
{% endblock %}

{% block javascript_inline %}
$(document).ready(function () {
    $(".pagination").rPage();
});
{% endblock %}

btdht_search/templates/btdht_search/top.html
{% extends "btdht_search/base.html" %}
{% load i18n %}
{% load btdht_search %}

{% block title %}BTDHT | top torrents{% if torrents.page > 1 %}, page {{torrents.page}}{% endif %}{% endblock %}
{% block extra_head %}
<link rel="alternate" type="application/rss+xml" href="{% url "btdht_search:top_rss" category %}" title="rss"/>
{% endblock %}

{% block pre_content %}
<div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h1 id="app-name">
                    {% if settings.BTDHT_LOGO_URL %}<img src="{{settings.BTDHT_LOGO_URL}}" alt="btdht-logo" />{% endif %}
                    {% trans "BTDHT Search" %}
                </h1>
              </div>
            </div>
{% endblock %}


{% block content2 %}
{% if settings.BTDHT_ADS_TEMPLATE %}{% include settings.BTDHT_ADS_TEMPLATE %}{% endif %}
<h1 id="top">Top Torrents
<a href="{% url "btdht_search:top_rss" category %}"><i class="fa fa-rss pull-right" aria-hidden="true" style="color:#fb8c00"></i></a>
</h1>
<div class="text-center">
<a class="btn btn-default{% if category == 0 %} active{% endif %}" href="{% if torrents.page == 1 %}{% url "btdht_search:top_index" %}{% else %}{% url "btdht_search:top" 0 torrents.page %}{% endif %}">All</a>
{% for cat in const.categories %}
<a class="btn btn-default{% if category == forloop.counter %} active{% endif %}" href="{% url "btdht_search:top" forloop.counter torrents.page %}">{{cat}}</a>
{% endfor %}
</div>
<br/>
{% include "btdht_search/torrent_table.html" %}
{% endblock %}

{% block javascript_inline %}
$(document).ready(function () {
    $(".pagination").rPage();
});
{% endblock %}