btdht_crawler/urls.py
# -*- coding: utf-8 -*-
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License version 3 for
# more details.
#
# You should have received a copy of the GNU General Public License version 3
# along with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# (c) 2015-2016 Valentin Samir
"""urls for the app"""
from django.conf.urls import url

from .utils import require_login, token_auth

import views

app_name = "btdht_crawler"

urlpatterns = [
    url('^$', require_login(views.index), name='index'),
    url('^download/(?P<hex_hash>[0-9A-Fa-f]{40})/(?P<name>.*)\.torrent$', require_login(views.download_torrent), name='download_torrent'),
    url('^(?P<token>[0-9A-Fa-f]{32})/download/(?P<hex_hash>[0-9A-Fa-f]{40})/(?P<name>.*)\.torrent$', token_auth(views.download_torrent), name='download_torrent'),
    url('^torrent/(?P<hex_hash>[0-9A-Fa-f]{40})/(?P<name>.*)$', require_login(views.info_torrent), name='info_torrent'),
    url('^torrent/(?P<hex_hash>[0-9A-Fa-f]{40}).json$', require_login(views.api_info_torrent), name='api_info_torrent'),
    url('^(?P<token>[0-9A-Fa-f]{32})/torrent/(?P<hex_hash>[0-9A-Fa-f]{40}).json$', token_auth(views.api_info_torrent), name='api_info_torrent_token'),
    url('^search/(?P<query>.*)/(?P<page>[0-9]+)/(?P<order_by>[1-7])/(?P<asc>[0-1])$', require_login(views.index), name='index_query'),
    url('^search/(?P<query>.*)/(?P<page>[0-9]+).json', require_login(views.api_search), name='api_search'),
    url('^(?P<token>[0-9A-Fa-f]{32})/search/(?P<query>.*)/(?P<page>[0-9]+).json', token_auth(views.api_search), name='api_search_token'),
    url('^recent$', require_login(views.recent), name='recent_index'),
    url('^recent.json$', require_login(views.api_recent), name='api_recent_index'),
    url('^recent/(?P<page>[0-9]+)$', require_login(views.recent), name='recent'),
    url('^recent/(?P<page>[0-9]+).json', require_login(views.api_recent), name='api_recent'),
    url('^(?P<token>[0-9A-Fa-f]{32})/recent.json$', token_auth(views.api_recent), name='api_recent_index_token'),
    url('^(?P<token>[0-9A-Fa-f]{32})/recent/(?P<page>[0-9]+).json', token_auth(views.api_recent), name='api_recent_token'),
    url('^stats$', require_login(views.stats), name='stats'),
    url('^api$', require_login(views.api), name='api'),
    url('^about$', require_login(views.about), name='about'),
]

btdht_crawler/templates/btdht_crawler/about.html
{% extends "btdht_crawler/base.html" %}
{% load i18n %}
{% load btdht_crawler %}

{% block title %}BTDHT | About{% endblock %}

{% block content2 %}
<h1>Overview</h1>
<p>
<a href="{{""|absolute_url:request}}">BTDHT Search</a> is a BitTorrent DHT search engine.<br/>
BitTorrent is a file sharing protocol.</br>
A DHT stand for Distributed Hash Table, the bittorent DHT, is a decentralized database used to find
peers distributing content.</br>
A torrent is a file with metadata which describes distributed content.
</p>

<p>
BTDHT Search's database is formed by DHT users.<br/>
BTDHT Search participates in the bittorent DHT network and follows the bittorent DHT protocol specification.</br>
The project name is an acronym for Bittorrent Distributed Hash Table Search.
</p>

<p>
BTDHT Search is not a tracker and doesn't store any content and only collects
torrent metadata (such as file names and file sizes) and a magnet link (torrent identifier). 
</p>
{% endblock %}

btdht_crawler/templates/btdht_crawler/api.html
{% extends "btdht_crawler/base.html" %}
{% load i18n %}
{% load btdht_crawler %}

{% block title %}BTDHT | API{% endblock %}

{% block content2 %}
<h1>API</h1>
{% if request.user.is_authenticated and user_pref %}
<p>You API token: <pre>{{user_pref.token}}</pre></p>
{% endif %}
<p>
<p>You can consult the database using the JSON following json API:</p>
<ul>
  <li>
    For fetcthing search results :
    {% url "btdht_crawler:api_search" "AZERTYUIOP" 123456789 as search_url %}
    <pre>{{search_url|replace:"AZERTYUIOP:<query>"|replace:"123456789:<page_nb>"|absolute_url:request}}</pre>
    For instance:
{% url "btdht_crawler:api_search" "debian" 1 as search_url %}
<pre>
$ curl {{search_url|absolute_url:request}}
[
 {
  "peers": 0, 
  "seeds": 1, 
  "hash": "7661229811ef32014879ceedcdf4a48f256c88ba", 
  "name": "debian-8.4.0-i386-netinst.iso", 
  "complete": 0, 
  "created": 1477188735, 
  "last_scrape": 1477319941, 
  "file_nb": 1, 
  "score": 0.5714285714285714, 
  "size": 331350016
 }, 
 {
  "peers": 0, 
  "seeds": 0, 
  "hash": "3abddf1c551b4a5da02413dcd71fce0599e01d04", 
  "name": "debian-8.0.0-i386-netinst.iso", 
  "complete": 0, 
  "created": 1477014396, 
  "last_scrape": 1477319941, 
  "file_nb": 1, 
  "score": 0.5714285714285714, 
  "size": 330301440
 }, 
...
]
</pre>
  </li>
  <li>
  For reading a specific torrent info:
  {% url "btdht_crawler:api_info_torrent" "EFF64C9D27332054112405897710C51BB3DBB6DD" as torrent_url%}
  <pre>{{torrent_url|replace:"EFF64C9D27332054112405897710C51BB3DBB6DD:<torrent hex hash>"|absolute_url:request}}</pre>
  For instance :
  {% url "btdht_crawler:api_info_torrent" "7661229811ef32014879ceedcdf4a48f256c88ba" as torrent_url%}
<pre>
$ curl {{torrent_url|absolute_url:request}}
{
 "peers": 0, 
 "seeds": 1, 
 "hash": "7661229811ef32014879ceedcdf4a48f256c88ba", 
 "name": "debian-8.4.0-i386-netinst.iso", 
 "complete": 0, 
 "created": 1477188735, 
 "last_scrape": 1477319941, 
 "file_nb": 1, 
 "size": 331350016
}
</pre>
  </li>
  <li>
  Fetching recent torrents:
  {% url "btdht_crawler:api_recent" 123456789 as recent_url %}
  <pre>{{recent_url|replace:"123456789:<page_nb>"|absolute_url:request}}</pre>
  For instance:
{% url "btdht_crawler:api_recent" 1 as recent_url %}
<pre>
$ curl {{recent_url|absolute_url:request}}
curl http://127.0.0.1:8000/recent/1.json
[
 {
  "peers": 9, 
  "seeds": 10, 
  "hash": "410660b3744984876f31c68d2dd2cf56e4a5d3af", 
  "name": "SNIS-659FHD.mp4", 
  "complete": 1637, 
  "created": 1477321297, 
  "last_scrape": 1477321383, 
  "file_nb": 1, 
  "size": 7470086567
 }, 
 {
  "peers": 0, 
  "seeds": 12, 
  "hash": "a61776bf5d01764a338296166ccdea7287fa49ca", 
  "name": "The.Wave.2016.TRUEFRENCH.DVDRIP-www.lien-torrent.com.com.avi", 
  "complete": 15, 
  "created": 1477321297, 
  "last_scrape": 1477321383, 
  "file_nb": 1, 
  "size": 1137139826
 }, 
...
]
</pre>
  </li>
</ul>
Page 1 always exists. You will get a 404 not found error if trying to fetch above the last page
{% endblock %}

btdht_crawler/templates/btdht_crawler/base.html
{% load i18n %}{% load staticfiles %}{% get_current_language as LANGUAGE_CODE %}<!DOCTYPE html>
<html{% if LANGUAGE_CODE %} lang="{{LANGUAGE_CODE}}"{% endif %}>
    <head>
        <meta charset="utf-8">
        <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% trans "BTDHT Search"  %}{% endblock %}</title>
        <link href="{{settings.BTDHT_COMPONENT_URLS.bootstrap3_css}}" rel="stylesheet">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="{{settings.BTDHT_COMPONENT_URLS.html5shiv}}"></script>
        <script src="{{settings.BTDHT_COMPONENT_URLS.respond}}"></script>
        <![endif]-->
        {% if settings.BTDHT_FAVICON_URL %}<link rel="shortcut icon" href="{{settings.BTDHT_FAVICON_URL}}" />{% endif %}
        <link href="{% static "btdht_crawler/styles.css" %}" rel="stylesheet">
        {% block extra_head %}{% endblock %}
    </head>
    <body>
    {% include "btdht_crawler/navbar.html" %}
      <div id="wrap">
        <div class="container">
           {% block container %}
           {% block pre_content %}{% endblock %}
            <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-2 col-xs-0"></div>
            <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
            {% include "btdht_crawler/messages.html" %}
            {% block content %}{% endblock %}
            </div>
            <div class="col-lg-3 col-md-3 col-sm-2 col-xs-0"></div>
            </div>
            <div class="row" id="content2">{% block content2 %}{% endblock %}</div>
        {% endblock %}
        </div> <!-- /container -->
       </div>
     <div style="clear: both;"></div>
      <script src="{{settings.BTDHT_COMPONENT_URLS.jquery}}"></script>
      <script src="{{settings.BTDHT_COMPONENT_URLS.bootstrap3_js}}"></script>
      <script src="{% static "btdht_crawler/responsive-paginate.js" %}"></script>
      {% block javascript %}{% endblock %}
      <script type="text/javascript">
{% block javascript_inline %}{% endblock %}
</script>
    </body>
</html>
<!--
Powered by django-btdht-crawler version {{VERSION}}

Pypi: https://pypi.python.org/pypi/django-btdht-crawler
github: https://github.com/nitmir/django-btdht-crawler
-->

btdht_crawler/templates/btdht_crawler/form.html
{% load btdht_crawler %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&#215;</button>
  {{error}}
</div>
{% endfor %}
{% for field in form %}{% if not field|is_hidden %}
<div class="form-group
  {% if not form.non_field_errors %}
    {% if field.errors %} has-error
    {% elif form.cleaned_data %} has-success
    {% endif %}
  {% endif %}"
>{% spaceless %}
  {% if field|is_checkbox %}
    <div class="checkbox"><label for="{{field.auto_id}}">{{field}}{{field.label}}</label></div>
  {% else %}
    <label class="control-label" for="{{field.auto_id}}">{{field.label}}</label>
    {{field}}
  {% endif %}
  {% for error in field.errors %}
    <span class="help-block">{{error}}</span>
  {% endfor %}
{% endspaceless %}</div>
{% else %}{{field}}{% endif %}{% endfor %}

btdht_crawler/templates/btdht_crawler/index.html
{% extends "btdht_crawler/base.html" %}
{% load i18n %}
{% load btdht_crawler %}
{% block title %}{% if query %}BTDHT | {{query}}{% else %}{% trans "BTDHT Search"  %}{% endif %}{% endblock %}
{% block pre_content %}
<div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h1 id="app-name">
                    {% if settings.BTDHT_LOGO_URL %}<img src="{{settings.BTDHT_LOGO_URL}}" alt="btdht-logo" />{% endif %}
                    {% trans "BTDHT Search" %}
                </h1>
              </div>
            </div>
{% endblock %}
{% block content %}
<form class="form-search" method="post" id="search_form">
{% csrf_token %}
{% include "btdht_crawler/form.html" %}
<button class="btn btn-primary btn-block btn-lg" type="submit">{% trans "Search" %}</button>
</form>
{% endblock %}


{% block content2 %}
{% if torrents %}<h1 id="results">Search results</h1>{% endif %}
{% include "btdht_crawler/torrent_table.html" %}
{% endblock %}

{% block javascript_inline %}
$(document).ready(function () {
    $(".pagination").rPage();
});
window.location.replace("#");
{% endblock %}

btdht_crawler/templates/btdht_crawler/navbar.html
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "btdht_crawler:index" %}">BTDHT</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% url "btdht_crawler:index" as index_url %}
            {% url "btdht_crawler:recent_index" as recent_url %}
            {% url "btdht_crawler:stats" as stats_url %}
            {% url "btdht_crawler:api" as api_url %}
            {% url "btdht_crawler:about" as about_url %}
            <li{% if request.path == index_url %} class="active"{% endif %}><a href="{{index_url}}">Home</a></li>
            <li{% if recent_url in request.path %} class="active"{% endif %}><a href="{{recent_url}}">Recent torrents</a></li>
            <li{% if stats_url == request.path %} class="active"{% endif %}><a href="{{stats_url}}"><span class="hidden-sm">Statistics</span><span class="glyphicon glyphicon-stats visible-sm"</span></a></li>
            <li{% if api_url == request.path %} class="active"{% endif %}><a href="{{api_url}}"><span class="hidden-sm">API</span><span class="glyphicon glyphicon-tasks visible-sm"</span></a></li>
            <li{% if about_url == request.path %} class="active"{% endif %}><a href="{{about_url}}"><span class="hidden-sm">About</span><span class="glyphicon glyphicon-info-sign visible-sm"</span></a></li>
          </ul>
          {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url "logout" %}"><span class="glyphicon glyphicon-off"</span></a></li>
          </ul>
          {% endif %}
          <form class="navbar-form navbar-right" role="search" method="post" action="{% url "btdht_crawler:index" %}">
            {% csrf_token %}
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="query" id="srch-term" value="{% if query %}{{query}}{% elif request.session.query %}{{request.session.query}}{% endif %}" required="">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
              </div>
            </div>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

btdht_crawler/templates/btdht_crawler/recent.html
{% extends "btdht_crawler/base.html" %}
{% load i18n %}
{% load btdht_crawler %}

{% block title %}{% trans "BTDHT | recent torrents"  %}{% endblock %}

{% block pre_content %}
<div class="row">
              <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h1 id="app-name">
                    {% if settings.BTDHT_LOGO_URL %}<img src="{{settings.BTDHT_LOGO_URL}}" alt="btdht-logo" />{% endif %}
                    {% trans "BTDHT Search" %}
                </h1>
              </div>
            </div>
{% endblock %}


{% block content2 %}
<h1 id="recent">Recent torrents</h1>
{% include "btdht_crawler/torrent_table.html" %}
{% endblock %}

{% block javascript_inline %}
$(document).ready(function () {
    $(".pagination").rPage();
});
{% endblock %}

btdht_crawler/templates/btdht_crawler/stats.html
{% extends "btdht_crawler/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block title %}BTDHT | Statistics{% endblock %}
{% block content2 %}
<h1>Statistics</h1>
<h2>Torrent chart</h2>
<canvas id="myChart" height="400" width="1000"></canvas>

<h2>Tracker scrape</h2>
<p>
Leecher/seeders/complete info are retreived from the trackers bellow.
The result from the tracker with the maximum leecher/seeders/complete is displayed.
</p>
<h3>Trackers that respond to scrape requests</h3>
{% if good_tracker %}
<ul>
{% for tracker in good_tracker %}
<li>{{tracker}}</li>
{% endfor%}
</ul>
{% endif %}
<h3>Trackers that do NOT respond to scrape requests</h3>
{% if bad_tracker %}
<ul>
{% for tracker in bad_tracker %}
<li>{{tracker}}</li>
{% endfor%}
</ul>
{% endif %}
{% endblock %}


{% block javascript %}
<script src="{{settings.BTDHT_COMPONENT_URLS.chart_js}}"></script>
{% endblock %}


{% block javascript_inline %}
//$("#myChart").attr("height", $("#wrap").height() - 300);
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: {{times|safe}},
        datasets: [
          {
            label: '# indexed torrents',
            data: {{torrent_indexed|safe}},
            fill: true,
            backgroundColor: "rgba(239, 83, 80, 0.5)",
            borderColor: "rgba(239, 83, 80, 1)",
            pointBorderColor: "transparent",
            pointBackgroundColor: "transparent",
            pointHoverBackgroundColor: "rgba(183, 28, 28, 1)",
            pointHoverBorderColor: "rgba(183, 28, 28, 1)",
             
          },
{% comment %}
          {
            label: '# tracked torrent hashes',
            data: {{hash_tracked|safe}},
            fill: true,
            //backgroundColor: "rgba(66, 165, 245, 0.5)",
            //borderColor: "rgba(66, 165, 245, 1)",
            //pointBorderColor: "rgba(66, 165, 245, 1)",
            //pointBackgroundColor: "rgba(66, 165, 245, 1)",
            //pointHoverBackgroundColor: "rgba(21, 101, 192, 1)",
            //pointHoverBorderColor: "rgba(21, 101, 192, 1)",
            
          },
{% endcomment %}
        ]
    },
    options: {
        maintainAspectRatio: false,
        responsive: false,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }],
            xAxes: [{
                type: 'time',
                time: {
                    parser: 'YYYY-MM-DD HH:mm:ss Z',
                    displayFormats: {
                        minute: 'HH:mm',
                        hour: 'MMM D, H\\h',
                    }
                }
            }]
        }
    }
});
{% endblock %}

btdht_crawler/templates/btdht_crawler/torrent.html
{% extends "btdht_crawler/base.html" %}
{% load i18n %}
{% load btdht_crawler %}

{% block title %}BTDHT | {{torrent.name}}{% endblock %}

{% block content2 %}
<br/>
<h1>Torrent infos</h1>
<table class="table">
<tr><th>Name</th><td>{{torrent.name}}</td></tr>
<tr><th>Files</th><td>{% if torrent.files %}<a href="#torrent_files">{{torrent.file_nb}}</a>{% else %}{{torrent.file_nb}}{% endif %}</td></tr>
<tr><th>Size</th><td>{{torrent.size_pp}} ({{torrent.size}} Bytes)</td></tr>
<tr><th>Uploaded</th><td>{{torrent.created_pp}}</td></tr>
<tr><th>Info Hash</th><td>{{torrent.hex_hash.upper}}</td></tr>
</table>
<h2>Torrent status</h2>
<p class="pull-left">Last scrape at {{torrent.last_scrape|date_pp}}.</p>
<form method="post" class="pull-left">
{% csrf_token %}
<input type="hidden" name="scrape" value="1"/>
<a href="#" onclick="$(this).closest('form').submit();"><span class="glyphicon glyphicon-refresh"></span></a>
</form>
<table class="table">
<tr><th>Seeders</th><td>{{torrent.seeds}}</td></tr>
<tr><th>Leechers</th><td>{{torrent.peers}}</td></tr>
<tr><th>Completed</th><td>{{torrent.complete}}</td></tr>
</table>
{% if not settings.BTDHT_HIDE_MAGNET_FROM_UNAUTH or not settings.BTDHT_HIDE_TORRENT_LINK_FROM_UNAUTH or request.user.is_authenticated %}
<h2>Download Links</h2>
<div class="row">
  <div class="col-lg-3 col-md-3 col-sm-2 col-xs-0"></div>
  <div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">
    <ul class="list-group">
      {% if not settings.BTDHT_HIDE_MAGNET_FROM_UNAUTH or request.user.is_authenticated %}
      <li class="list-group-item">
        <a href="{{torrent.magnet}}">
          <button type="button" class="btn btn-success btn-block btn-lg">
            <span class="glyphicon glyphicon-magnet" aria-hidden="true"></span> Magnet
          </button>
        </a>
      </li>
      {% endif %}
      {% if not settings.BTDHT_HIDE_TORRENT_LINK_FROM_UNAUTH or request.user.is_authenticated %}
      {% if torrent.url %}
      <li class="list-group-item">
        <a href="{{torrent.url}}">
          <button type="button" class="btn btn-info btn-block btn-lg">
            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span> Torrent file
          </button>
        </a>
      </li>
      {% endif %}
      {% endif %}
    </ul>
  </div>
  <div class="col-lg-3 col-md-3 col-sm-2 col-xs-0"></div>
</div>
{% endif %}
{% if torrent.files %}
<h2 id="torrent_files">Torrent Files</h2>
<table class="table table-striped table-condensed table-responsive">
<tr><th>Path</th><th>Size</th></tr>
{% for file in torrent.files %}
<tr><td>{{file.path}}</td><td class="text-nowrap">{{file.size|size_pp}}</td></tr>
{% endfor %}
</table>
{% endif %}
{% endblock %}

btdht_crawler/templates/btdht_crawler/torrent_table.html
{% if torrents %}
<table class="table table-striped table-condensed table-responsive">
<tr>
  <th></th>
  <th width="100%">
    {% if torrents.url_sort_by_name %}
    <a href="{{torrents.url_sort_by_name}}">Name</a>
      {% if torrents.order_by == const.ORDER_BY_NAME %}
        <span class="pull-right glyphicon glyphicon-triangle-{% if torrents.asc %}top{% else %}bottom{% endif %}"></span>
      {% endif %}
    {% else %}
    Name
    {% endif %}
  </th>
  <th class="text-nowrap">
    {% if torrents.url_sort_by_size %}
    <a href="{{torrents.url_sort_by_size}}">Size</a>
      {% if torrents.order_by == const.ORDER_BY_SIZE %}
        <span class="glyphicon glyphicon-triangle-{% if torrents.asc %}top{% else %}bottom{% endif %}"></span>
      {% endif %}
    {% else %}
    Size
    {% endif %}
  </th>
  <th class="text-nowrap">
    {% if torrents.url_sort_by_created %}
    <a href="{{torrents.url_sort_by_created}}">Created</a>
      {% if torrents.order_by == const.ORDER_BY_CREATED %}
        <span class="glyphicon glyphicon-triangle-{% if torrents.asc %}top{% else %}bottom{% endif %}"></span>
      {% endif %}
    {% else %}
    Created
    {% endif %}
  </th>
  <th class="text-nowrap">
    {% if torrents.url_sort_by_files %}
    <a href="{{torrents.url_sort_by_files}}">Files</a>
      {% if torrents.order_by == const.ORDER_BY_FILES %}
        <span class="glyphicon glyphicon-triangle-{% if torrents.asc %}top{% else %}bottom{% endif %}"></span>
      {% endif %}
    {% else %}
    Files
    {% endif %}
  </th>
  <th class="text-nowrap">
    {% if torrents.url_sort_by_seeds %}
    <a href="{{torrents.url_sort_by_seeds}}">seeds</a>
      {% if torrents.order_by == const.ORDER_BY_SEEDS %}
        <span class="glyphicon glyphicon-triangle-{% if torrents.asc %}top{% else %}bottom{% endif %}"></span>
      {% endif %}
    {% else %}
    seeds
    {% endif %}
  </th>
  <th class="text-nowrap">
    {% if torrents.url_sort_by_peers %}
    <a href="{{torrents.url_sort_by_peers}}">peers</a>
      {% if torrents.order_by == const.ORDER_BY_PEERS %}
        <span class="glyphicon glyphicon-triangle-{% if torrents.asc %}top{% else %}bottom{% endif %}"></span>
      {% endif %}
    {% else %}
    peers
    {% endif %}
  </th>
</tr>
{% for t in torrents %}
<tr>
  <td class="text-nowrap">
    {% if not settings.BTDHT_HIDE_MAGNET_FROM_UNAUTH or request.user.is_authenticated %}
    <a title="magnet link" href="{{t.magnet}}">
      <span class="glyphicon glyphicon-magnet" aria-hidden="true"></span>
    </a>
    {% endif %}
    {% if not settings.BTDHT_HIDE_TORRENT_LINK_FROM_UNAUTH or request.user.is_authenticated %}
    <a title="download the torrent file" href="{% url "btdht_crawler:download_torrent" t.hex_hash t.name %}">
      <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
    </a>
    {% endif %}
  </td>
  <td><a href="{% url "btdht_crawler:info_torrent" t.hex_hash t.name %}">{{t.name}}</a></td>
  <td class="text-nowrap">{{t.size_pp}}</td>
  <td class="text-nowrap">{{t.created_pp}}</td>
  <td class="text-nowrap">{{t.file_nb}}</td>
  <td class="text-nowrap">{% if t.seeds is not None %}{{t.seeds}}{% endif %}</td>
  <td class="text-nowrap">{% if t.peers is not None %}{{t.peers}}{% endif %}</td>
</tr>
{% endfor %}
</table>
{% endif %}
{% if torrents.start_page != torrents.end_page %}
<div class="text-center">
<nav aria-label="...">
  <ul class="pagination pagination-sm">
    {% for page in torrents.pages %}
        <li{% if page.class %} class="{{page.class}}"{% endif %}>
          {% if page.url %}<a href="{{page.url}}">{{page.name|safe}}</a>{% else %}<span>{{page.name|safe}}</span>{% endif %}
        </li>
    {% endfor %}
  </ul>
</nav>
</div>
{% endif %}